In [2]:
#NumPy Fundamentals Practice

In [3]:
import numpy as np

In [ ]:
Array Creation

In [1]:
import numpy as np

#1D array
arr1= np.array([1,2,3,4,5])
print("1D array:", arr1)

#2D array
arr2= np.array([[1,2,3], [4,5,6]])
print("2D array:\n",arr2)

#Zeros and Ones
zeros= np.zeros((2,3))
ones= np.ones((3,3))
print("Zeros:\n",zeros)
print("Ones:\n",ones)

#Range and Linspace
range_arr= np.arange(0,10,2)
linspace_arr= np.linspace(0,1,5)
print("Range array:",range_arr)
print("Linspace array:",linspace_arr)

1D array: [1 2 3 4 5]
2D array:
 [[1 2 3]
 [4 5 6]]
Zeros:
 [[0. 0. 0.]
 [0. 0. 0.]]
Ones:
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
Range array: [0 2 4 6 8]
Linspace array: [0.   0.25 0.5  0.75 1.  ]


In [ ]:
Indexing & Slicing

In [2]:
arr= np.array([10,20,30,40,50])
print("First element:",arr[0])
print("Slice 1:4:",arr[1:4])
print("Last element:",arr[-1])
matrix= np.array([[1,2,3],[4,5,6],[7,8,9]])
print("Element at (1,2):",matrix[1,2])
print("First row:",matrix[0,:])
print("First column:",matrix[:,0])

First element: 10
Slice 1:4: [20 30 40]
Last element: 50
Element at (1,2): 6
First row: [1 2 3]
First column: [1 4 7]


In [ ]:
Broadcasting

In [3]:
arr= np.array([1,2,3])
print("Add scalar:",arr + 5)
print("Multiply scalar:",arr*2)
matrix= np.array([[1,2],[3,4]])
print("Matrix+10:\n",matrix+10)

Add scalar: [6 7 8]
Multiply scalar: [2 4 6]
Matrix+10:
 [[11 12]
 [13 14]]


In [ ]:
Vectorized Operations

In [5]:
a= np.array([1,2,3])
b= np.array([4,5,6])
print("Addition:",a+b)
print("Multiplication:",a*b)
print("Dot product:",np.dot(a,b))

Addition: [5 7 9]
Multiplication: [ 4 10 18]
Dot product: 32


In [ ]:
Matrix Operations

In [6]:
a= np.array([[1,2],[3,4]])
b= np.array([[5,6],[7,8]])
print("Matrix Multiplication:\n",np.dot(a,b))
print("Transpose:\n", np.transpose(a))
print("Inverse:\n", np.linalg.inv(a))

Matrix Multiplication:
 [[19 22]
 [43 50]]
Transpose:
 [[1 3]
 [2 4]]
Inverse:
 [[-2.   1. ]
 [ 1.5 -0.5]]


In [ ]:
Useful Functions

In [8]:
arr= np.array([1,2,3,4,5])
print("Mean:",np.mean(arr))
print("Standard Deviation:",np.std(arr))
print("Sum:",np.sum(arr))
print("Max:",np.max(arr))
print("Min:",np.min(arr))

Mean: 3.0
Standard Deviation: 1.4142135623730951
Sum: 15
Max: 5
Min: 1
